### ISSUE TITLE
Browser stop redrawing on resize.

### ISSUE THREAD

**Issue by ekalchev** [cefsharp/CefSharp#2492]
### Bug Report

- **What version of the product are you using?**
    65

- **What architecture x86 or x64?**
x86

- **On what operating system?**
    - Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF + Winforms control

- **What steps will reproduce the problem?**
   I provided reproducible sample application https://ufile.io/jfzop

- **What is the expected output? What do you see instead?**
To work!

- **Please provide any additional information below.**

It seems browser rendering is get broken if you resize the browser window while a page is loading and you have the settings below. Commenting this line

         settings.CefCommandLineArgs.Add("disable-gpu-vsync", "1"); //Disable Vsync

 fixes the problem. I guess this will be only reproducible on machines with GPU.

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**

Yes, if you enable  these options and resize the window

            settings.CefCommandLineArgs.Add("disable-gpu", "1");
            settings.CefCommandLineArgs.Add("disable-gpu-compositing", "1");
            settings.CefCommandLineArgs.Add("disable-gpu-vsync", "1"); //Disable Vsync

**Comment by ekalchev** [comment]
Took me two days to figure out what is causing this. I hope someone to look at this sample app that is reproducing the issue.
https://ufile.io/jfzop

**Comment by ekalchev** [comment]
Yes, I can reproduce this with the sample WinForms application. 

You just need to add this as start up arguments

        settings.CefCommandLineArgs.Add("disable-gpu", "1");
        settings.CefCommandLineArgs.Add("disable-gpu-compositing", "1");
        settings.CefCommandLineArgs.Add("disable-gpu-vsync", "1"); //Disable Vsync

open microsoft.com and resize the windows while loading.

**Comment by ekalchev** [comment]
This is reproducible with cefclient 3.3325.1758 but not with latest 3.3440.1805.gbe070f9. I guess it was fixed.

**Comment by amaitland** [comment]
You can try `67.0.0-pre01` which is based on `3.3396.1786.gd3e36d0 / Chromium 67.0.3396.79` if you haven't already tried a `3396` branched version.

`master` is currently based on `3.3440.1803` you can use a `CI` build if your game, seehttps://github.com/cefsharp/CefSharp#releases-1

Closing as `upstream`.

**Comment by xzycn** [comment]
@wuruile Maybe you could try to use v71.0.0-pre01 now, otherwise v71.0.0 in a couple of days.It solves my problem :)

**Comment by TGolias** [comment]
@xzycn @wuruile I can confirm the problem still exists on v71.0.0. That's actually one of the big reasons I may have to use WinForms version hosted in a WindowsFormsHost for the project I'm working on.

Weirdly I noticed that minimizing the Window hosting the WPF WebBrowser then maximizing it causes the browser to start redrawing again. If this gives anyone any ideas on a workaround let me know, I'd be willing to give them a shot.

-and if I end up finding anything I'll be sure to post my findings here.

**Comment by amaitland** [comment]
There is another bug in CEF causing problems on resize, you can track the progress at https://bitbucket.org/chromiumembedded/cef/issues/2614/osr-resizing-issue-surface-invariants

**Comment by CaptBli** [comment]
Similar to @TGolias, we have a couple of browsers that we use for two different sets of data.  When it stops rendering we have to switch to the other browser and back and it starts rendering again.
