### ISSUE TITLE
WPF - WpfKeyboardHandler uses modifiers as lParam resulting in incorrect event code

### ISSUE THREAD

**Issue by igandrews** [cefsharp/CefSharp#3462]
- **What version of the product are you using?**
Nuget 87.1.132.0

- **What architecture x86 or x64?**
x64
	
- **What version of .Net?**
 .net 4.5.2
    
- **On what operating system?**
Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF
    
- **What steps will reproduce the problem?**
Run the CefSharp sample from the repo
Browse to https://keycode.info/
Focus within the browser
Press and release ctrl key => event.code reports Digit3
Hold ctrl key and press z => event.code reports Digit3
Press shift key => event.code reports Digit1

- **What is the expected output? What do you see instead?**
Expected output is that either the _code_ property is empty or that it has the correct info (pressing left ctrl => ControlLeft, pressing right ctrl=>ControlRight). For me I'd be happy if you just passed 0 for that parameter which is in essence what is done when no modifiers are pressed. 
The CefBrowserHostWrapper uses the lParam as the native_key_code so it's wrong to pass the modifier state for that param. I assume that the actual lParam for a WM_KEYDOWN is expected (repeat count, scan code, etc) but it's hard to tell. The only thing the lParam seems to be used for within the CefBrowserHostWrapper is to obtain the extended bit and that would seem to jive with what the 24th bit of the lParam for WM_KEYDOWN would hold.

- **Please provide any additional information below.**
The problem would seem to be the lParam (3rd param) here:
https://github.com/cefsharp/CefSharp/blob/bbb5afaeb3696aa083a4a7fcd591a7c1bdad90f7/CefSharp.Wpf/Internals/WpfKeyboardHandler.cs#L79

- **Does this problem also occur in the `CEF` Sample Application**
No. In that app the code is correctly reported.

**Comment by amaitland** [comment]
I'm aware it needs a rewrite, you can implement your own IWpfKeyboardHandler without needing to build the project from source, so you can easily test out any proposed changes you'd like to make.

The  http://cefsharp.github.io/api/88.2.x/html/M_CefSharp_IBrowserHost_SendKeyEvent.htm should be used directly rather than using the http://cefsharp.github.io/api/88.2.x/html/M_CefSharp_IBrowserHost_SendKeyEvent_1.htm version.

The cefclient source for reference https://github.com/chromiumembedded/cef/blob/023d218104a319bb27940bc22779195d6de36513/tests/cefclient/browser/osr_window_win.cc#L776

Pull requests welcome.

**Comment by amaitland** [comment]
The SendKeyEvent method has some know issues so it's likely we can get a perfect implementation until https://bitbucket.org/chromiumembedded/cef/issues/2597/windows-windowless-keyboard-handling is resolved.

**Comment by igandrews** [comment]
Thx for the prompt response. Yes I see that there are some aspects outside of the cef impl involved as well. For me I'd be ok with not passing erroneous info - i.e. just passing 0 as the lParam. At least then the _code_ property is empty as it would in browsers that don't support that. I cannot imagine that anyone is currently relying on _code_ being "Digit1" for shift or "Digit3" for control so it's worse that its present and wrong. The page I was loading was checking that code is provided and not something like "Unspecified" and then relying on that being valid and only if not provided would it fall back to the keycode. So for now I've derived from the included keyboardhandler (the ime one in my case) to override HandleKeyPress and duplicate the existing impl except passing 0 for the lParam.

**Comment by amaitland** [comment]
> without needing to build the project from source, so you can easily test out any proposed changes you'd like to make.

Test your proposed change and submit a pull request.

**Comment by igandrews** [comment]
Thx. If it matters, I wasn't going to leave it. I had actually spent a little time trying a different approach to triggering the SendKeyEvent via an HwndSource so it would have access to the scancode (rather than trying to infer it back from the vkey and keyboard layout) and while passing the scancode as the lparam was _better_ it was still not consistent with what you get in chrome or via the chromium cefclient.exe. Things like right Ctrl, left/right alt, left/right windows keys, etc. either resulted in an empty code or an incorrect one. I didn't seem to get any better results using the overload that took a KeyEvent either so guess its some issue within the host - maybe even related to that other issue you linked to. So I left it alone for now and figured I'd try to revisit it at a later time since the workaround fixed the immediate issue. Anyway thanks again for incorporating the change.

**Comment by amaitland** [comment]
> Thx. If it matters, I wasn't going to leave it

Great 👍 I'll be releasing version 89 in the few days, so the window for changes is pretty much closed.

> it was still not consistent with what you get in chrome or via the chromium cefclient.exe

cefclient needs to be run with the following command line args to be comparable to the WPF implementation. 

```
cefclient --multi-threaded-message-loop --off-screen-rendering-enabled --enable-gpu --no-sandbox --disable-site-isolation-trials
```

A quick test and and the results were almost the same as the WPF version, was a very quick test though.

The current implementation doesn't set the key pad modifier as lparam is required to have KF_EXTENDED bit set

- We could potentially use something like https://stackoverflow.com/a/54641046/4583726 to create lparam
- Set only the KF_EXTENDED bit for keypad keys

The keyboard handler does need a rewrite,  I'll likely hold off until CEF has finished it's rewrite. 

Improvements in the form of pull requests are welcome 👍
