### ISSUE TITLE
PrintToPdf - PdfPrintSettings - Custom Margins do not work

### ISSUE THREAD

**Issue by TomasPojezny-IdeaStatiCa** [cefsharp/CefSharp#4466]
- **What version of the product are you using?**
Nuget 110.0.300

- **What architecture x86 or x64?**
x64
	
- **What version of .Net?**
Net 4.8
    
- **On what operating system?**
Win11

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF
    
- **What steps will reproduce the problem?**

> 		private static PdfPrintSettings GetPdfPrintSettings()
> 		{
> 			double MillimetersToInches (double millimeter) => millimeter / 25.4;
> 			
> 			return new PdfPrintSettings
> 			{
> 				PaperWidth = MillimetersToInches(210.0),
> 				PaperHeight = MillimetersToInches(297.0),
> 
> 				// NOTE: Margins input does not seem to work in CefSharp version 110.0.300
> 				MarginType = CefPdfPrintMarginType.Custom,
> 				MarginLeft = MillimetersToInches(20.0),
> 				MarginTop = MillimetersToInches(30.0),
> 				MarginRight = MillimetersToInches(10.0),
> 				MarginBottom = MillimetersToInches(25.0),
> 
> 				PrintBackground = true
> 			};
> 		}
> 		
> 		// ...
> 		
> 		webBrowserHost.GetBrowser().GetHost().PrintToPdf(dialog.FileName, GetPdfPrintSettings(), callback);

- **What is the expected output? What do you see instead?**
Expected specified margins, instead default margins

**Comment by amaitland** [comment]
> * **What version of the product are you using?**
>   Nuget 110.0.300

Please test with the current release.

> Custom Margins do not work

`CefSharp` does little more than populate the structure and call the underlying `CEF method`. So I suspect this is a problem in [CEF](https://github.com/chromiumembedded/cef)

https://github.com/cefsharp/CefSharp/blob/v112.2.70/CefSharp.Core.Runtime/Internals/CefBrowserHostWrapper.cpp#L96

https://github.com/chromiumembedded/cef/blob/5615/include/internal/cef_types.h#L2536

If the problem reproduces in the current supported version then it's probably worth stepping through with the debugger to confirm the correct values is being passed through. On the surface it looks like an upstream issue in CEF.

**Comment by aimcosoftware** [comment]
I've implemented PDF.js, which gives you complete control https://mozilla.github.io/pdf.js/

**Comment by hronlukas** [comment]
Hi, I've tested it with 115.3.130 and still it doesn't work.

**Comment by amaitland** [comment]
> stepping through with the debugger to confirm the correct values is being passed through. On the surface it looks like an upstream issue in CEF.

Build the project from source, confirm the values are being passed through correctly. The actual implementation is at the `CEF/Chromium` level.

**Comment by amaitland** [comment]
Closing as `upstream`. If this still reproduces with the current supported version of `CEF` (M121 at time of writing) then you'll need to raise an issue at https://github.com/chromiumembedded/cef/issues

**Comment by hopfen-heiner** [comment]
Still happens in 121, I've created an issue [here](https://github.com/chromiumembedded/cef/issues/3651).
