### ISSUE TITLE
Ctrl+Shift does not work in CefSharp WPF

### ISSUE THREAD

**Issue by ralphmayr** [cefsharp/CefSharp#743]
The state of the Ctrl (and Alt and Shift) keys is not forwarded to the web app running in CefSharp in WPF. (Basically the same problem as we had it in #542 with mouse events)

**Comment by amaitland** [comment]
Are you able to test with https://github.com/cefsharp/CefSharp/tree/cef/2171?

I ended up making major changes to the keyboard handling code.

**Comment by ralphmayr** [comment]
I just tested the behavior with the cef/2171 branch and am able to reproduce it there as well.

**Comment by amaitland** [comment]
Any chance you could re-target your PR against `cef/2171`? It's looking more and more likely we'll skip a `37` point release and move onto a `39` release.

**Comment by ralphmayr** [comment]
Sure, will do that!

**Comment by amaitland** [comment]
Thanks :+1:

**Comment by amaitland** [comment]
FYI I've just merged `cef/2171` into `master`

**Comment by jankurianski** [comment]
@ralphmayr I'm trying to reproduce this problem in CefSharp `master` by launching CefSharp.Wpf.Example, navigating to http://javascript.info/tutorial/keyboard-events#test-stand-test-stand and pressing Ctrl+Shift, Alt, etc.  The keys are being detected.

I also tried http://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_event_mouse_ctrlkey which tests the ctrlKey modifier on mouse clicks, and it can detect the Ctrl key.

Maybe I am misunderstanding the problem - what am I missing from my steps?

**Comment by ralphmayr** [comment]
That's strange... I explicitly tested the behavior with the current CefSharp 39.0.0-pre2 binaries (from nuget) as well as the master branch from github now, and couldn't recreate it any more, either.

Possibly some of the other changes made for 39 fixed that issue as well? (I tested it some time ago on the cef2171 branch where the issue still existed...)

Anyway, as far as this is concerned we can close the bug as well as the related PR #782.
Thanks!

**Comment by amaitland** [comment]
@ralphmayr Great news! If it turns out there's still a problem then feel free to reopen!
